<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{31400cb4-b4cb-40c4-b7a1-915ff1e2cd27}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	my_counter : INT := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[my_counter := my_counter + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>